name: test-py39-functional-microshift

on:
  push:
  pull_request:
    branches: [ main ]

env:
  KUBECONFIG: ${{ github.workspace }}/kubeconfig

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade and install packages
        run: |
          bash ./ci/setup-ubuntu.sh

      - name: Install oc/kubectl clients
        run: |
          bash ./ci/setup-oc-client.sh

      - name: Install Microshift
        run: |
          ./ci/microshift.sh

      - name: Install ColdFront and plugin
        run: |
          ./ci/setup.sh

      - name: Run functional tests
        run: |
          ./ci/run_functional_tests_openshift.sh
